### PR TITLE
[✨] Functioning Settings Menu, (Not fully completed) 

### PR DESCRIPTION
**Pull request by RisingGlitch**
[✨] Functioning Settings Menu

 I will finish my rewrite for the settings app later.

### CODE REVIEW

**Comment by idk-pixel** [comment]
not sure if its just me but dynamic was useless last time. might want to switch that one with rammerhead as its sometimes better than ultraviolet

**Comment by idk-pixel** [comment]
image
just remove the const url = to fix the ts standard since an error can still show up even if its not stored

**Comment by RisingGlitch** [comment]
> image just remove the const url = to fix the ts standard since an error can still show up even if its not stored

I don't think you understand the code at all...

That line checks if the URL is valid or not by checking if it results in a error when converted.

**Comment by idk-pixel** [comment]
> > image just remove the const url = to fix the ts standard since an error can still show up even if its not stored
> 
> 
> 
> I don't think you understand the code at all...
> 
> 
> 
> That line checks if the URL is valid or not by checking if it results in a error when converted.

I understand what the code does. I'm saying you need to remove the variable as it's not needed or used. You have to remove the code for making the variable not the actual code assigned to it

**Comment by ghost** [comment]
@idk-pixel is very correct, you do not need to have the `const` there as it is an unused variable which `ts-standard` does not like...

**Pull request closed without merging**
